# Generated by Django 4.2.7 on 2023-12-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_category_alter_blog_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Política', 'Política'), ('Tecnología', 'Tecnología'), ('Ciencia', 'Ciencia'), ('Humor', 'Humor')], default='Humor', max_length=100),
        ),
    ]
